### ISSUE TITLE
Bridge.ReactRouting docs?

### ISSUE THREAD

**Issue by sambomartin** [ProductiveRage/Bridge.ReactRouting#2]
Hi PR, just wondered if you have any notes on how to use ReactRouting?

Thanks

**Comment by Zaid-Ajaj** [comment]
@sambomartin  +1, a dummy example project would really nice to have

**Comment by ProductiveRage** [comment]
I've been a bit negligent with documentation for this project, I'm afraid! I hope to rectify that soon with a proper README but, for now, I've included an example project in the repo with an explanation of what's going on (and the primary aims of the project) in the comments.

Let me know if it doesn't makes sense or if you would like anything clarifying.

**Comment by ProductiveRage** [comment]
Just wanted to let you both know that I've finally written up some documentation - there is now a README available on the repo home page.

Hopefully it has enough information to get going (and explains why the project exists, rather than just being a binding to an existing router).

There have been a few breaking changes over the last week but I think that they are all improvements and I thought that now was the best time to make them (while the documentation was thin on the ground and so before many people were likely using the code yet).

Let me know if you would like to offer any more information or clear anything up.

**Comment by Zaid-Ajaj** [comment]
@ProductiveRage  Wow, must have taken you a lot of work to put this together, Thanks a lot!!!
