### ISSUE TITLE
Container using store does not render when going back in browser

### ISSUE THREAD

**Issue by dnaustin** [ProductiveRage/Bridge.ReactRouting#6]
I have set up routing in my app and I can move from my first container that uses a store to a second container that just renders a div at the moment. When I click the back button, the first container should be rendered but it is not. Debugging it shows that the state is not defined which suggests that the store is not invoking its change action when the page is being re-routed to. I tried adding an option for my NavigateTo action in the dispatcher.receive section of the store to invoke the change action but that doesn't seemed to have worked.

**Comment by ProductiveRage** [comment]
If you clone this repo, you get set the "ExampleHost" project to be the startup project and that will give you a complete sample to play with.

I think that the first step (if you haven't already!) would be to double-check that that project works for you as intended and then maybe see if there are any obvious differences between how it works and how your code works?

**Comment by dnaustin** [comment]
I have been following the Example project but it doesn't use a Store to render the containers which is where the issue seems to be. I copied and pasted in the navigation links component into my project, added it to my initial container, updated the navigator to my methods (see below) and tried it out but it doesn't work.

Inside my "main" div (when I navigate back to the first container) it shows a noscript tag which also happens if I were to not fire the initial StoreInitialised action in my app startup.
    <noscript data-reactid=".0"></noscript>

**Comment by dnaustin** [comment]
public class PADSNavigator : Navigator
    {
        private readonly Func<UrlPathDetails> getSearch;
        private readonly Func<int, UrlPathDetails> getOverview;

        public PADSNavigator(AppDispatcher dispatcher) : base(dispatcher)
        {
            if (dispatcher == null)
            {
                throw new ArgumentNullException(nameof(dispatcher));
            }

            // Register search route
            getSearch= AddRelativeRoute(
                segments: NonNullList<string>.Empty,
                routeAction: new NavigateToSearch(),
                urlGenerator: () => GetPath()
                );

            // Register "/Overview/{int}"
            getOverview = AddRelativeRoute(
                routeDetails: RouteBuilder.Empty.Fixed("Overview").Int(),
                routeActionGenerator: matchedValue => new NavigateToOverview(matchedValue),
                urlGenerator: segment => GetPath("Overview", segment)
                );
        }

        public UrlPathDetails Search() { return getSearch(); }
        public UrlPathDetails Overview(int segment) { return getOverview(segment); }
    }

**Comment by dnaustin** [comment]
Would it be possible to add a store into the example project to see how it integrates with the router as I cannot get it working with a store?

I also cannot get it to work when moving to a container that uses a store that isn't the initial page load.

EDIT: I have managed to get it working but it feels like a bit of a hack. In my store, when it receives the appropriate navigation action from the dispatcher it will fire off a StoreInitialised action to the dispatcher to then get the store to render properly.

    .Else<NavigateToSearch>(action =>                 
    {
        Window.SetTimeout(() => dispatcher.Dispatch(new StoreInitialised(this)));
    })

**Comment by ProductiveRage** [comment]
That doesn't sounds like it should be too much work, I'll try to look into extending the example tonight or tomorrow.

Since you've included that workaround, it's made me think - in the tutorial posts, a **StoreInitialised** action is required in order for the application to know that everything is loaded and that the Store can do whatever it needs to. When there is routing involved, the matching of the route can take the place of the **StoreInitialised** action (the navigated-to-whatever action will tell the Store to get started and a separate **StoreInitialised** action should not be needed). So, in your code, could it be as simple as removing the **StoreInitialised** class entirely and doing whatever work you needed to do in that action handler in the action handler that matches **NavigateToSearch**?

**Comment by ProductiveRage** [comment]
I've added some stores to the example project. There is no **StoreInitialised** action required, the navigation actions have two purposes now - one to determine what component should be mounted and the second purpose is to allow stores to update themselves if they are interested in the particular action (for example, the **HomeStore** will update its state if a **NavigateToHome** action occurs).

In the example project, each time that the User navigates, a "RequestedAt" value will be updated (when a **NavigateToHome** action occurs, the **HomeStore** will update its "RequestedAt" property while other navigation actions will result in other stores updating *their* state). Note that as you move forward and backwards through the URLs (either by clicking navigation link *or* by using the browser's back / forward buttons), the "Page navigated to at.." time will always increase; if the User clicks back to go to a previous URL then this will be identified as a new navigation and the "Page navigated to at.." will be the current time and *not* the time that the User last went to that URL. This is important because it proves that every navigation action (even a "back" click) is interpreted as a new navigation action and you have the opportunity to update any of your application's state that you need to.

Hopefully this clears things up a bit!

**Comment by dnaustin** [comment]
Thanks for adding the store examples on - it all links up how I was expecting. Turns out the issue was that I didn't override GetInitialState in my container. As the NavigateTo action was occuring before ComponentDidMount had taken place, the container's state wasn't being set. My original workaround would have sent the StoreInitialised action after the component had mounted and subsequently set the state properly.

**Comment by ProductiveRage** [comment]
For my real applications, I try to capture patterns like this in code so that it's harder to forget anything - for example, there is obvious duplication across the three components "HomeContainer", "AccommodationListContainer" and "AccommodationSectionContainer" where they all have to subscribe to their Store's Change event when they are mounted and unsubscribe after they are unmounted and set state both in GetInitialState _and_ when the Stores change. I didn't want to make the routing example too complicated, so that it wouldn't scare anyone away, but you might be interested to know that I would do something like the following to try to remove this duplication (and the associated potential for error where repeated code crops up again and again) -

1. I would create an abstract Container class that has a props reference that has a "Store" property on it (this requires an "IHaveStore" interface) -
```
public abstract class Container<TProps, TState, TStore> : Component<TProps, TState>
    where TProps : IHaveStore<TStore>
    where TStore : Store
{
    protected Container(TProps props, params Union<ReactElement, string>[] children)
        : base(props, children) { }

    protected sealed override TState GetInitialState() => UpdateState();
    protected sealed override void ComponentDidMount() => props.Store.Change += StoreChanged;
    protected sealed override void ComponentWillUnmount() => props.Store.Change -= StoreChanged;
    private void StoreChanged() => UpdateState();

    protected abstract TState UpdateState();
}

public interface IHaveStore<TStore> where TStore : Store
{
    TStore Store { get; }
}

```
2. I would add the IHaveStore interface to each of the Props classes that my Containers use - eg. the Props class for "HomeContainer" would change from:
```

public sealed class Props : IAmImmutable
{
    public Props(HomeStore store, ExampleNavigator navigator)
    {
        this.CtorSet(_ => _.Store, store);
        this.CtorSet(_ => _.Navigator, navigator);
    }
    public HomeStore Store { get; }
    public ExampleNavigator Navigator { get; }
}

```
to
```

public sealed class Props : IAmImmutable, IHaveStore<HomeStore>
{
    public Props(HomeStore store, ExampleNavigator navigator)
    {
        this.CtorSet(_ => _.Store, store);
        this.CtorSet(_ => _.Navigator, navigator);
    }
    public HomeStore Store { get; }
    public ExampleNavigator Navigator { get; }
}

```

3. I would then change the base class for each container component from being Component<Props, State> to Container<Props, State, Store> and then the four GetInitialState / ComponentDidMount / ComponentWillUnmount / StoreChanged methods are all replaced with a single method:

`protected override State UpdateState() => new State(props.Store.RequestedAt);`

This means that the HomeContainer class now looks like this:
```

public sealed class HomeContainer : Container<HomeContainer.Props, HomeContainer.State, HomeStore>
{
    public HomeContainer(HomeStore store, ExampleNavigator navigator) : base(new Props(store, navigator)) { }

    protected override State UpdateState() => new State(props.Store.RequestedAt);

    public override ReactElement Render()
    {
        if (!state.RequestedAt.IsDefined)
            return null;

        return DOM.Div(null,
            new NavigationLinks(props.Navigator, new ClassName("main-nav")),
            DOM.Div(new Attributes { ClassName = "content" }, "The Home Page"),
            new NavigatedToTime(state.RequestedAt.Value)
        );
    }

    public sealed class Props : IAmImmutable, IHaveStore<HomeStore>
    {
        public Props(HomeStore store, ExampleNavigator navigator)
        {
            this.CtorSet(_ => _.Store, store);
            this.CtorSet(_ => _.Navigator, navigator);
        }
        public HomeStore Store { get; }
        public ExampleNavigator Navigator { get; }
    }

    public sealed class State : IAmImmutable
    {
        public State(Optional<DateTime> requestedAt)
        {
            this.CtorSet(_ => _.RequestedAt, requestedAt);
        }
        public Optional<DateTime> RequestedAt { get; }
    }
}

```
The other container classes look very similar, there is much less duplication and the compiler will tell you if you create a new class that is derived from Container and you forget to add an "UpdateState" method!

I'm a big fan of making it possible for the compiler to catch developer mistakes and introducing patterns like this helps with that! As I said, I only didn't do this in the ReactRouting example because I didn't want to make it look too scary and complex but I think that anything bigger than the smallest toy project probably benefits from this sort of design! I'm very glad that the Bridge / Visual Studio / C# combination makes it possible!

(@dnaustin I _think_ that you will get a notification of this comment but I'm not 100% sure since the comment comes after my closing the issue.. so just mentioning you by name here, too, to be sure!)

**Comment by dnaustin** [comment]
Wow thank you for the in depth post! Reducing the duplication in the container makes a lot of sense and this seems like a great way of doing it. 

I may be wrong but I think the StoreChanged method should call SetState in order to persist the change:
`private void StoreChanged() => SetState(UpdateState());`

**Comment by ProductiveRage** [comment]
Oops, yes - good catch! :)
